name: add/modify Activity
description: 'Type: activity'
title: 'add/modify Activity: <enter item name>'
body:
-   type: markdown
    attributes:
        value: " To add a new %(id)s please fill in the form below. \n Existing entries\
            \ are: %(contains)s \n Alternatively "
-   id: description
    attributes:
        label: Description
        description: A detailed description of the activity or project.
    validations:
        required: true
    type: input
-   id: id
    attributes:
        label: Id
        description: A unique identifier for the activity.
    validations:
        required: true
    type: input
-   id: name
    attributes:
        label: Name
        description: The name of the activity.
    validations:
        required: true
    type: input
-   id: type
    attributes:
        label: Type
        description: The type of entity being described (e.g., 'activity').
        options:
        - activity
    validations:
        required: true
    type: dropdown
-   id: url
    attributes:
        label: Url
        description: A URL providing further documentation or references.
    validations:
        required: true
    type: input
