{'body': [{'attributes': {'value': ' To add a new %(id)s please fill in the '
                                   'form below. \n'
                                   ' Existing entries are: %(contains)s \n'
                                   ' Alternatively '},
           'type': 'markdown'},
          {'attributes': {'description': 'The context for the data, usually a '
                                         'URL or a reference to external '
                                         'definitions.',
                          'label': '@Context',
                          'placeholder': 'Enter your @context'},
           'id': '@context',
           'type': 'input',
           'validations': {'required': True}},
          {'attributes': {'description': 'A unique identifier for the '
                                         'activity.',
                          'label': 'Id',
                          'placeholder': 'Enter your id'},
           'id': 'id',
           'type': 'input',
           'validations': {'required': True}},
          {'attributes': {'description': 'The type of entity being described '
                                         "(e.g., 'activity').",
                          'label': 'Type',
                          'options': ['activity'],
                          'placeholder': ''},
           'id': 'type',
           'type': 'dropdown',
           'validations': {'required': True}},
          {'attributes': {'description': 'A detailed description of the '
                                         'activity or project.',
                          'label': 'Description',
                          'placeholder': 'Enter your description'},
           'id': 'description',
           'type': 'input',
           'validations': {'required': True}},
          {'attributes': {'description': 'The name of the activity.',
                          'label': 'Name',
                          'placeholder': 'Enter your name'},
           'id': 'name',
           'type': 'input',
           'validations': {'required': True}},
          {'attributes': {'description': 'A URL providing further '
                                         'documentation or references.',
                          'label': 'Url',
                          'placeholder': 'Enter your url'},
           'id': 'url',
           'type': 'input',
           'validations': {'required': True}}],
 'description': None,
 'name': 'add/modify Activity',
 'title': 'add/modify Activity: <enter item name>'}
