########################################################################
# How to create a YAML issue template form in your repository          #
########################################################################
# To use a YAML issue form in your repository:
# 1. Create a file in `.github/ISSUE_TEMPLATE/` within your repository.
# 2. Name the file appropriately, e.g., `bug.yaml`.
# 3. Add the YAML structure below to define your form.
#
# Note: Existing Markdown templates in `.github/ISSUE_TEMPLATE` will
#       continue to work and don't need to be removed.
########################################################################

########################################################################
# Required top-level fields                                            #
########################################################################
# The name is a string that's unique across all templates:
name: Bug Report
# The description is a short summary (max 200 characters) for this template:
description: Use this template to report bugs in the project.

########################################################################
# Optional top-level fields                                            #
########################################################################
# Pre-fill the issue title field (optional):
title: "[BUG] Describe the issue briefly"
# Automatically assign labels to issues created using this template:
labels: ["bug", "needs-triage"]
# Automatically assign users to issues created with this template:
assignees:
  - maintainer1
  - maintainer2

########################################################################
# User Input Body                                                      #
########################################################################
body:
  ######################################################################
  # Example Input Fields                                               #
  ######################################################################

  # CHECKBOX:
  - type: checkboxes
    id: bug_checklist
    attributes:
      label: Bug Checklist
      description: Confirm the following before submitting your report.
      options:
        - label: I have searched for duplicates.
        - label: I have included detailed steps to reproduce the bug.
        - label: I have attached logs or screenshots if applicable.
    validations:
      required: true

  # DROPDOWN:
  - type: dropdown
    id: bug_severity
    attributes:
      label: Severity Level
      description: Select the severity of the bug.
      options:
        - Low
        - Medium
        - High
        - Critical
    validations:
      required: true

  # TEXTAREA:
  - type: textarea
    id: bug_description
    attributes:
      label: Bug Description
      description: Provide a detailed description of the issue.
      placeholder: "Describe the issue, including observed vs expected behavior."
    validations:
      required: true

  # TEXTAREA WITH PLACEHOLDER:
  - type: textarea
    id: bug_reproduction_steps
    attributes:
      label: Steps to Reproduce
      description: Provide step-by-step instructions to reproduce the issue.
      placeholder: |
        1. Open the application.
        2. Navigate to the user settings page.
        3. Observe the error when clicking "Save."
    validations:
      required: true

  # INPUT FIELD:
  - type: input
    id: bug_impact
    attributes:
      label: Impact Scope
      description: Briefly explain who or what this bug affects.
      placeholder: "Affects all users on version X."
    validations:
      required: false

  # MARKDOWN SECTION:
  - type: markdown
    attributes:
      value: |
        ### Notes
        - Please ensure all fields are completed as accurately as possible.
        - For help, refer to our [contribution guidelines](https://github.com/your-repo/contributing).

########################################################################
# Notes                                                               #
########################################################################
# - Ensure `validations: required: true` is used only when necessary.
# - YAML supports multi-line values using `|` or `>`.
########################################################################
