body:
- attributes:
    description: Your full name
    label: Name
    placeholder: Enter your name
    required: true
  id: name
  type: input
- attributes:
    description: Your email address
    label: Email
    placeholder: Enter your email
    required: true
  id: email
  type: input
- attributes:
    description: Your age
    label: Age
    placeholder: Enter your age
    required: false
  id: age
  type: input
- attributes:
    description: Select your favorite color
    label: Favorite Color
    options:
    - Red
    - Green
    - Blue
    - Yellow
    required: false
  id: favorite_color
  type: dropdown
- attributes:
    description: Select your skills
    label: Skills
    options:
    - label: Python
      value: python
    - label: JavaScript
      value: javascript
    - label: C++
      value: c++
    - label: Java
      value: java
    required: false
  id: skills
  type: checkboxes
- attributes:
    description: Are you currently active?
    label: Is Active
    options:
    - 'Yes'
    - 'No'
    required: false
  id: is_active
  type: dropdown
description: Auto-generated form from JSON Schema.
name: Example Form Schema
title: '{{ name }} - Submission'

