body:
- attributes:
    description: Your full name
    label: Name
    placeholder: Enter your name
  id: name
  type: input
  validations:
    required: true 
    regex:"[A-D]"
- attributes:
    description: Your email address
    label: Email
    placeholder: Enter your email
  id: email
  type: input
  validations:
    required: true
- attributes:
    description: Your age
    label: Age
    placeholder: Enter your age
  id: age
  type: input
  validations:
    required: false
- attributes:
    description: Select your favorite color
    label: Favorite Color
    options:
    - Red
    - Green
    - Blue
    - Yellow
  id: favorite_color
  type: dropdown
  validations:
    required: false
- attributes:
    description: Select your skills
    label: Skills
    options:
    - label: python
    - label: javascript
    - label: c++
    - label: java
  id: skills
  type: checkboxes
  validations:
    required: false
- attributes:
    description: Are you currently active?
    label: Is Active
    options:
    - 'Yes'
    - 'No'
  id: is_active
  type: dropdown
  validations:
    required: false
description: Auto-generated form from JSON Schema.
name: Example Form Schema
title: '{{ name }} - Submission'

